version: "3.8"

services:
  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

  app:
    container_name: app
    build:
      context: .
    command: bash -c "alembic upgrade head && 
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    depends_on:
      - db

  redis:
    image: redis
    ports:
      - "6379:6379"

  celery_worker:
    container_name: celery_worker
    build: .
    command: celery -A app.celery_tasks.tasks worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - app
      - redis

  celery_beat:
    container_name: celery_beat
    build: .
    command: celery -A app.celery_tasks.tasks beat --loglevel=info
    depends_on:
      - app
      - redis